# Generated by Django 4.1 on 2022-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laymen_name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=20)),
                ('light', models.CharField(max_length=50)),
                ('water', models.CharField(max_length=200)),
                ('maintenance_level', models.IntegerField()),
            ],
        ),
    ]
