# Generated by Django 4.1 on 2022-08-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_watering_plant_alter_watering_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('X', 'Extra Large')], default='S', max_length=1)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
