# Generated by Django 4.1 on 2022-08-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pot_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(to='main_app.pot'),
        ),
    ]
